#-------------------------------
# General Site Settings

menu:
- {name: 'Research', url: 'pages/research.html'}
#- {name: 'Blog', url: 'pages/blog.html'}
#- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Andreea Radulescu is a robotics researcher.'
  rel-author: 'Andreea Radulescu'
  rel-publisher: 'Andreea Radulescu'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# About Section

about: >
  ## About Me - [CV](/files/docs/andreea_radulescu_cv.pdf)

  <img src="/files/imgs/All3_andreea.jpg" align="left" alt="Andreea Radulescu" style="width: 27.6%; display:inline;margin:17px 15px 2px 5px;"/>

  I am currently the Head of Control at [ALL3 Ltd.](https://www.all3.com), where I define and drive the development roadmap for the Mantis robotic platform, focused on automating construction-site operations. I lead the control team responsible for the architecture supporting dynamic locomotion and manipulation across our robotic fleet, while expanding the stack toward reinforcement learning and AI-driven methodologies.


  Previously (2021 - 2024) I was the Robotics Research Control Team Techlead at [Dyson Technology Ltd.](https://careers.dyson.com/en-gb/what-you-can-do/engineer/robotics/). I originally joined Dyson in 2019 as a Robotics Research Engineer and worked on delivering various control technology solution, as driven by the product requirement. The team I lead operated in close collaboration with other parts of the research group (mechanical design, electronics, perception, high level planning, safety).
  
  
  Between 2016 - 2019 I was a PostDoctoral Researcher in the [Dynamic Legged Systems Group](https://dls.iit.it) at the Italian Institute of Technology. My research focused on optimal control, machine learning and using variable impedance actuators for systems in domains with contacts. I was working on locomotion strategies for the [HyQ robot series](https://dls.iit.it/robots).
  
  
  I received my Ph.D (2016) and Msc (2011) in Intelligent Robotics from the University of Edinburgh,  working under the supervision of Prof. Sethu Vijayakumar. Previously, I graduated from the Polytechnic University of Bucharestâ€‰, with a BEng (2009) in Automatic Control and Applied Informatics.



contact: >
  # Contact

   If you'd like to know more about my research or would just like to discuss past or future projects, feel free to contact me [by email](mailto:andreearadulescu19@gmail.com) or through [LinkedIn](https://www.linkedin.com/in/andreearadulescu19081985/).

#-------------------------------
# Work Section

#projects:
#- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
#- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/rheea'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/andreearadulescu19081985/'}
- {icon: 'envelope', link: 'mailto:andreearadulescu19@gmail.com'}
- {icon: 'google', link: 'https://scholar.google.it/citations?user=I2yknQQAAAAJ&hl=en'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
